#!/bin/bash

set -e # If any of the steps fail, exit.

echo Running hooks/pre-commit...

detect_nci() {
  if git grep --cached --line-number -i no""checkin; then
    echo "The forbidden string was encountered; stopping."
    exit 42
  fi
}

detect_nci # Immediately run this before all other steps, because it is fast.

./build.sh
git add "A9 wordcounts.jd"
git add "site/chapters.json"

# Could our build process ever generate this string? IDK maybe.
detect_nci

echo "Pre-commit cleared successfully. ✓✓✓"
